.apex/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClientId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase</relationshipLabel>
        <relationshipName>Purchase</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemId__c</fullName>
        <label>ItemId</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>PurchaseLine</relationshipLabel>
        <relationshipName>PurchaseLine</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>PurchaseId</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLine</relationshipLabel>
        <relationshipName>PurchaseLine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>UnitCost</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/classes/purchaseController_Test.cls
@isTest
private class purchaseController_Test {

	@isTest
	static void testCreatePurchaseAndPurchaseLines_success() {
		// Create test Account
		Account testAccount = new Account(
				Name = 'Test Client'
		);
		insert testAccount;

		// Create test Item
		Item__c testItem = new Item__c(
				Name = 'Test Product',
				Price__c = 100.00
		);
		insert testItem;

		// Prepare JSON input
		List<Map<String, Object>> cartItems = new List<Map<String, Object>>();
		cartItems.add(new Map<String, Object>{
		'itemId' => testItem.Id,
		'amount' => 2,
		'unitCost' => 100.00
		});

		String cartItemsJson = JSON.serialize(cartItems);

		// Run test
		Test.startTest();
		Id resultPurchaseId = purchaseController.createPurchaseAndPurchaseLines(testAccount.Id, cartItemsJson);
		Test.stopTest();

		// Assertions
		System.assertNotEquals(null, resultPurchaseId, 'Purchase ID should not be null');

		// Query and verify inserted records
		Purchase__c insertedPurchase = [SELECT Id, Name, ClientId__c FROM Purchase__c WHERE Id = :resultPurchaseId];
		System.assertEquals(testAccount.Id, insertedPurchase.ClientId__c, 'Purchase should be linked to the correct Account');

		List<PurchaseLine__c> purchaseLines = [SELECT Id, PurchaseId__c, ItemId__c, Amount__c, UnitCost__c FROM PurchaseLine__c WHERE PurchaseId__c = :resultPurchaseId];
		System.assertEquals(1, purchaseLines.size(), 'One purchase line should be inserted');
		System.assertEquals(testItem.Id, purchaseLines[0].ItemId__c);
		System.assertEquals(2, purchaseLines[0].Amount__c);
		System.assertEquals(100.00, purchaseLines[0].UnitCost__c);
	}

	@isTest
	static void testCreatePurchaseAndPurchaseLines_missingInputs() {
		// Case 1: Null accountId
		Boolean exceptionThrown1 = false;

		// Case 2: Empty JSON
		Account acc = new Account(Name = 'Empty JSON Account');
		insert acc;

		Boolean exceptionThrown2 = false;


		Test.startTest();
		try {
			purchaseController.createPurchaseAndPurchaseLines(null, '[{}]');
		} catch (AuraHandledException e) {
			exceptionThrown1 = true;

		}

		try {
			purchaseController.createPurchaseAndPurchaseLines(acc.Id, '');
		} catch (AuraHandledException e) {
			exceptionThrown2 = true;

		}
		Test.stopTest();

	}
}