.apex/src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClientId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase</relationshipLabel>
        <relationshipName>Purchase</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemId__c</fullName>
        <label>ItemId</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>PurchaseLine</relationshipLabel>
        <relationshipName>PurchaseLine</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>PurchaseId</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLine</relationshipLabel>
        <relationshipName>PurchaseLine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>UnitCost</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/classes/purchaseController.cls
public class purchaseController {

	@AuraEnabled
	public static Id createPurchaseAndPurchaseLines(Id accountId, String cartItemsJson) {
		if (accountId == null || String.isBlank(cartItemsJson)) {
			throw new AuraHandledException('Account ID and cart items are required.' + String.isBlank(cartItemsJson));
		}

		List<Object> rawItems = (List<Object>) JSON.deserializeUntyped(cartItemsJson);

		List<PurchaseLine__c> purchaseLinesToInsert = new List<PurchaseLine__c>();
		for (Object obj : rawItems) {
			Map<String, Object> itemMap = (Map<String, Object>) obj;
			String itemId = (String) itemMap.get('itemId');
			Integer amount = (Integer) itemMap.get('amount');
			Decimal unitCost = (Decimal) itemMap.get('unitCost');

			purchaseLinesToInsert.add(new PurchaseLine__c(
					ItemId__c = Id.valueOf(itemId),
					Amount__c = amount,
					UnitCost__c = unitCost
			));
		}

		Account account = [SELECT Id, Name FROM Account WHERE Id = :accountId LIMIT 1];

		Purchase__c newPurchase = new Purchase__c(
				Name = 'Purchase - ' + account.Name + ' - ' + DateTime.now().format('MM/dd/yyyy HH:mm'),
				ClientId__c = account.Id
		);

		insert newPurchase;

		for (PurchaseLine__c line : purchaseLinesToInsert) {
			line.PurchaseId__c = newPurchase.Id;
		}

		insert purchaseLinesToInsert;

		return newPurchase.Id;
	}

}